In [2]:
%matplotlib inline
from matplotlib import style
style.use('fivethirtyeight')
import matplotlib.pyplot as plt

In [3]:
import numpy as np
import pandas as pd

In [4]:
import datetime as dt

# Reflect Tables into SQLAlchemy ORM

In [5]:
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [6]:
engine = create_engine("sqlite:///Resources/hawaii.sqlite")

In [9]:
# reflect an existing database into a new model
Base=automap_base()
Base.prepare(engine, reflect=True)

# reflect the tables

In [10]:
# We can view all of the classes that automap found
Base.classes.keys() #identify the keys in the hawaii database

['measurement', 'station']

In [11]:
# Save references to each table
Measurements=Base.classes.measurement #reflect the hawaii measurements into a "Measurements" table
Stations=Base.classes.station #reflect the hawaii stations into a "Stations" table

In [12]:
# Create our session (link) from Python to the DB
session = Session(engine)

# Exploratory Climate Analysis

In [14]:
# Design a query to retrieve the last 12 months of precipitation data and plot the results

# Calculate the date 1 year ago from the last data point in the database
session.query(Measurements.date).order_by(Measurements.date.desc()).first() #find the last date in the measurements table (2017-08-23)
#1 year from last data point '2016-08-23'

# Perform a query to retrieve the data and precipitation scores
session.query(Measurements.prcp).\
    filter(Measurements.date > '2016-08-23').all()

# Save the query results as a Pandas DataFrame and set the index to the date column

# Sort the dataframe by date

# Use Pandas Plotting with Matplotlib to plot the data

[(0.08),
 (0.08),
 (0.0),
 (0.0),
 (0.01),
 (0.0),
 (0.0),
 (0.13),
 (0.0),
 (0.0),
 (0.0),
 (0.03),
 (None),
 (None),
 (0.05),
 (0.0),
 (0.03),
 (0.0),
 (0.05),
 (0.0),
 (0.02),
 (1.32),
 (0.42),
 (0.06),
 (0.05),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.02),
 (0.0),
 (0.0),
 (0.0),
 (0.06),
 (0.02),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.01),
 (0.0),
 (0.0),
 (0.0),
 (0.05),
 (0.15),
 (0.01),
 (0.0),
 (0.03),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.24),
 (0.03),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.07),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.03),
 (0.05),
 (0.01),
 (0.13),
 (0.14),
 (0.05),
 (0.05),
 (0.05),
 (0.0),
 (0.01),
 (0.0),
 (0.14),
 (0.12),
 (0.03),
 (0.0),
 (0.03),
 (0.43),
 (0.02),
 (0.0),
 (0.03),
 (0.52),
 (0.05),
 (0.04),
 (0.01),
 (0.05),
 (0.03),
 (0.0),
 (0.0),
 (0.01),
 (0.13),
 (0.01),
 (0.0),
 (0.0),
 (0.01),
 (0.01),
 (0.01),
 (0.0),
 (0.02),
 (0.0),
 (0.02),
 (0.04),
 (0.12),
 (0.01),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.16),
 (0.0),
 (0.04),
 (0.03),
 (0.0),
 (0.0),
 (0.0),
 (0.18),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.51),
 (0.0),
 (0.0),
 (0.0),
 (0.31),
 (2.62),
 (0.01),
 (0.0),
 (0.0),
 (0.07),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.06),
 (0.06),
 (0.01),
 (0.0),
 (0.03),
 (0.0),
 (0.0),
 (0.0),
 (1.19),
 (0.73),
 (0.47),
 (0.0),
 (0.35),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.02),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.26),
 (0.01),
 (0.0),
 (0.02),
 (0.0),
 (0.02),
 (0.05),
 (0.23),
 (0.32),
 (0.03),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.12),
 (0.89),
 (0.26),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.01),
 (0.0),
 (0.0),
 (0.0),
 (0.05),
 (0.01),
 (0.0),
 (0.01),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.08),
 (0.13),
 (0.15),
 (0.01),
 (0.02),
 (0.0),
 (0.26),
 (0.02),
 (0.0),
 (0.0),
 (0.02),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.04),
 (0.08),
 (0.02),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.05),
 (0.0),
 (0.02),
 (0.0),
 (0.0),
 (0.0),
 (0.06),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.08),
 (0.02),
 (0.02),
 (0.04),
 (0.04),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.07),
 (0.02),
 (0.0),
 (0.02),
 (0.03),
 (0.05),
 (0.03),
 (0.0),
 (0.03),
 (0.0),
 (0.05),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.02),
 (0.0),
 (0.0),
 (0.02),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.02),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (2.15),
 (0.08),
 (0.03),
 (0.18),
 (0.14),
 (0.17),
 (0.0),
 (0.1),
 (0.0),
 (0.02),
 (0.07),
 (0.03),
 (0.11),
 (0.05),
 (0.1),
 (0.22),
 (0.01),
 (0.01),
 (0.18),
 (0.04),
 (0.37),
 (0.9),
 (0.12),
 (0.01),
 (0.04),
 (0.0),
 (0.01),
 (0.09),
 (0.06),
 (0.09),
 (0.15),
 (0.0),
 (0.02),
 (0.06),
 (0.12),
 (0.08),
 (0.49),
 (0.31),
 (0.14),
 (0.02),
 (0.04),
 (0.0),
 (0.0),
 (0.05),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.02),
 (0.03),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.03),
 (0.05),
 (0.06),
 (0.0),
 (0.15),
 (0.1),
 (0.01),
 (0.0),
 (0.04),
 (0.06),
 (0.11),
 (0.02),
 (0.02),
 (0.1),
 (0.03),
 (0.01),
 (0.0),
 (0.0),
 (0.0),
 (0.02),
 (0.02),
 (0.0),
 (0.14),
 (0.08),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.06),
 (0.0),
 (0.14),
 (0.03),
 (0.01),
 (0.11),
 (0.11),
 (0.02),
 (0.41),
 (0.03),
 (0.2),
 (0.05),
 (0.05),
 (0.06),
 (0.02),
 (0.04),
 (0.05),
 (0.33),
 (0.3),
 (0.04),
 (0.1),
 (0.34),
 (0.02),
 (0.17),
 (0.03),
 (0.34),
 (0.02),
 (0.02),
 (0.01),
 (0.1),
 (0.05),
 (0.02),
 (0.01),
 (0.11),
 (0.29),
 (0.21),
 (0.02),
 (0.03),
 (0.17),
 (0.1),
 (0.14),
 (0.03),
 (0.26),
 (0.03),
 (0.09),
 (0.18),
 (0.21),
 (0.62),
 (0.29),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.06),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.04),
 (0.01),
 (0.08),
 (0.15),
 (0.12),
 (0.0),
 (0.0),
 (0.14),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.16),
 (1.08),
 (1.08),
 (0.02),
 (0.0),
 (1.0),
 (1.07),
 (2.9),
 (0.0),
 (0.0),
 (0.0),
 (0.8),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.06),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.16),
 (2.2),
 (1.45),
 (0.54),
 (0.0),
 (0.1),
 (0.51),
 (0.0),
 (0.0),
 (0.8),
 (0.13),
 (0.03),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.19),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.6),
 (0.13),
 (0.0),
 (0.0),
 (0.03),
 (0.0),
 (0.08),
 (0.0),
 (0.0),
 (0.0),
 (0.08),
 (0.04),
 (0.04),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.01),
 (0.03),
 (0.03),
 (0.27),
 (0.69),
 (0.45),
 (0.49),
 (0.41),
 (0.08),
 (0.02),
 (0.33),
 (1.16),
 (1.01),
 (0.02),
 (0.0),
 (0.0),
 (0.0),
 (0.1),
 (2.6),
 (0.35),
 (1.21),
 (0.07),
 (0.03),
 (0.01),
 (0.0),
 (0.0),
 (0.0),
 (0.07),
 (0.22),
 (1.62),
 (0.05),
 (0.03),
 (0.04),
 (0.02),
 (0.05),
 (0.08),
 (0.03),
 (0.02),
 (0.09),
 (0.02),
 (0.0),
 (0.0),
 (0.0),
 (0.02),
 (0.58),
 (0.37),
 (0.02),
 (0.0),
 (0.29),
 (0.02),
 (0.2),
 (0.1),
 (0.03),
 (0.1),
 (0.2),
 (0.15),
 (0.0),
 (0.0),
 (0.0),
 (0.02),
 (0.02),
 (0.21),
 (0.24),
 (0.19),
 (0.36),
 (0.27),
 (0.17),
 (0.02),
 (0.35),
 (0.25),
 (0.05),
 (0.05),
 (0.02),
 (0.1),
 (0.0),
 (0.0),
 (0.08),
 (0.02),
 (0.0),
 (0.01),
 (0.03),
 (0.04),
 (0.06),
 (0.05),
 (0.13),
 (0.03),
 (0.0),
 (0.0),
 (0.02),
 (0.02),
 (0.09),
 (0.0),
 (0.01),
 (0.01),
 (0.33),
 (0.05),
 (0.03),
 (0.07),
 (0.12),
 (0.03),
 (0.0),
 (0.12),
 (0.0),
 (0.07),
 (0.06),
 (0.58),
 (0.03),
 (0.06),
 (0.0),
 (0.13),
 (0.06),
 (0.0),
 (0.0),
 (2.28),
 (0.0),
 (0.02),
 (0.02),
 (0.14),
 (0.04),
 (None),
 (0.0),
 (0.19),
 (None),
 (0.04),
 (0.23),
 (0.01),
 (0.29),
 (None),
 (0.32),
 (1.84),
 (0.07),
 (0.07),
 (None),
 (0.25),
 (0.02),
 (0.17),
 (0.15),
 (0.0),
 (0.0),
 (0.02),
 (0.0),
 (0.0),
 (0.2),
 (0.06),
 (0.08),
 (0.03),
 (0.03),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (None),
 (0.04),
 (0.0),
 (0.02),
 (0.0),
 (0.02),
 (None),
 (0.03),
 (0.0),
 (0.01),
 (0.03),
 (None),
 (0.01),
 (0.0),
 (0.2),
 (0.07),
 (0.26),
 (0.14),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.13),
 (0.02),
 (0.17),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.05),
 (0.0),
 (0.18),
 (0.0),
 (None),
 (None),
 (0.02),
 (0.03),
 (0.0),
 (0.04),
 (0.03),
 (0.07),
 (0.4),
 (0.26),
 (0.0),
 (0.2),
 (None),
 (0.02),
 (0.26),
 (0.0),
 (None),
 (0.34),
 (0.12),
 (0.07),
 (0.0),
 (0.0),
 (0.04),
 (0.0),
 (0.0),
 (0.09),
 (0.05),
 (0.03),
 (0.13),
 (None),
 (0.02),
 (0.01),
 (0.56),
 (0.29),
 (0.36),
 (0.0),
 (0.01),
 (0.0),
 (0.0),
 (0.0),
 (0.59),
 (0.0),
 (0.03),
 (0.0),
 (0.0),
 (0.0),
 (None),
 (0.0),
 (None),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (0.02),
 (None),
 (None),
 (0.01),
 (0.0),
 (0.0),
 (None),
 (0.0),
 (0.0),
 (0.0),
 (0.0),
 (None),
 (0.04),
 (0.9),
 (0.0),
 (0.0),
 (0.0),
 (2.39),
 (1.91),
 (0.0),
 (0.0),
 (0.0),
 (0.62),
 (0.06),
 (None),
 (0.0),
 (0.11),
 (0.0),
 (0.0),
 (None),
 (0.0),
 (0.04),
 (1.12),
 (None),
 (None),
 (0.0),
 (0.0),
 (0.5),
 (0.13),
 (None),
 (0.0),
 (0.0),
 (None),
 (0.06),
 (0.0),
 (None),
 (0.0),
 (0.0),
 (0.0),
 (0.15),
 (None),
 (0.0),
 (0.03),
 (0.03),
 (0.0),
 (0.0),
 (0.0),
 (0.09),
 (0.0),
 (0.07),
 (0.0),
 (0.0),
 (None),
 (0.0),
 (0.16),
 (0.29),
 (0.0),
 (0.29),
 (None),
 (0.12),
 (0.0),
 (0.0),
 (1.05),
 (0.7),
 (None),
 (0.0),
 (0.14),
 (0.02),
 (0.09),
 (0.95),
 (1.17),
 (0.03),
 (0.01),
 (0.01),
 (0.08),
 (0.28),
 (0.06),
 (0.95),
 (0.52),
 (0.0),
 (None),
 (None),
 (0.05),
 (0.0),
 (0.16),
 (0.01),
 (0.01),
 (None),
 (0.11),
 (0.1),
 (0.07),
 (0.0),
 (0.0),
 (0.02),
 (0.0),
 (0.04),
 (0.0),
 (0.0),
 (0.15),
 (0.16),
 (0.05),
 (0.02),
 (0.0),
 (0.0),
 (0.01),
 (0.0),
 (0.53),
 (0.14),
 (0.35),
 (0.1),
 (0.21),
 (0.3),
 (0.02),
 (0.02),
 (0.18),
 (0.19),
 (0.17),
 (None),
 (None),
 (None),
 (0.0),
 (None),
 (None),
 (None),
 (0.06),
 (0.0),
 (0.0),
 (0.0),
 (0.02),
 (0.3),
 (0.0),
 (0.01),
 (0.12),
 (0.16),
 (0.0),
 (0.09),
 (0.0),
 (0.0),
 (0.12),
 (0.07),
 (1.19),
 (0.12),
 (0.02),
 (0.0),
 (0.14),
 (0.02),
 (None),
 (0.12),
 (0.05),
 (0.01),
 (0.04),
 (0.0),
 (0.0),
 (0.1),
 (0.0),
 (0.0),
 (0.0),
 (None),
 (0.01),
 (0.0),
 (0.0),
 ...]

In [ ]:
# Use Pandas to calcualte the summary statistics for the precipitation data

In [ ]:
# Design a query to show how many stations are available in this dataset?

In [ ]:
# What are the most active stations? (i.e. what stations have the most rows)?
# List the stations and the counts in descending order.

In [ ]:
# Using the station id from the previous query, calculate the lowest temperature recorded, 
# highest temperature recorded, and average temperature of the most active station?

In [ ]:
# Choose the station with the highest number of temperature observations.
# Query the last 12 months of temperature observation data for this station and plot the results as a histogram

## Bonus Challenge Assignment

In [ ]:
# This function called `calc_temps` will accept start date and end date in the format '%Y-%m-%d' 
# and return the minimum, average, and maximum temperatures for that range of dates
def calc_temps(start_date, end_date):
    """TMIN, TAVG, and TMAX for a list of dates.
    
    Args:
        start_date (string): A date string in the format %Y-%m-%d
        end_date (string): A date string in the format %Y-%m-%d
        
    Returns:
        TMIN, TAVE, and TMAX
    """
    
    return session.query(func.min(Measurement.tobs), func.avg(Measurement.tobs), func.max(Measurement.tobs)).\
        filter(Measurement.date >= start_date).filter(Measurement.date <= end_date).all()

# function usage example
print(calc_temps('2012-02-28', '2012-03-05'))

In [ ]:
# Use your previous function `calc_temps` to calculate the tmin, tavg, and tmax 
# for your trip using the previous year's data for those same dates.

In [ ]:
# Plot the results from your previous query as a bar chart. 
# Use "Trip Avg Temp" as your Title
# Use the average temperature for the y value
# Use the peak-to-peak (tmax-tmin) value as the y error bar (yerr)

In [ ]:
# Calculate the total amount of rainfall per weather station for your trip dates using the previous year's matching dates.
# Sort this in descending order by precipitation amount and list the station, name, latitude, longitude, and elevation

In [ ]:
# Create a query that will calculate the daily normals 
# (i.e. the averages for tmin, tmax, and tavg for all historic data matching a specific month and day)

def daily_normals(date):
    """Daily Normals.
    
    Args:
        date (str): A date string in the format '%m-%d'
        
    Returns:
        A list of tuples containing the daily normals, tmin, tavg, and tmax
    
    """
    
    sel = [func.min(Measurement.tobs), func.avg(Measurement.tobs), func.max(Measurement.tobs)]
    return session.query(*sel).filter(func.strftime("%m-%d", Measurement.date) == date).all()
    
daily_normals("01-01")

In [ ]:
# calculate the daily normals for your trip
# push each tuple of calculations into a list called `normals`

# Set the start and end date of the trip

# Use the start and end date to create a range of dates

# Stip off the year and save a list of %m-%d strings

# Loop through the list of %m-%d strings and calculate the normals for each date

In [ ]:
# Load the previous query results into a Pandas DataFrame and add the `trip_dates` range as the `date` index

In [ ]:
# Plot the daily normals as an area plot with `stacked=False`